before_first_h2: ""
before_h2: ""
end_of_document: |
  <div class="web-only">
  <hr />
  <div>[donate content="If you'd like to see us extending our work in democracy further, please consider making a contribution."][/donate]</div>
  <hr />
  </div>
categories:
  - Repowering Democracy
  - Democracy
author: repoweringdemocracy