name: Update democracy subscribers

on:
  workflow_dispatch:
  schedule:
    # run every weekday as 7
    - cron: "0 7 * * 1-5"

jobs:

  send:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      # setup python 3.10
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false

      - name: Setup
        run: |
          pip install j2cli
          poetry install

      - uses: DamianReeves/write-file-action@v1.2
        with:
          path: template.md.j2
          contents: |
            {% for item in segments %}
            {{ item.name.replace("Interest: ", "") }}: {{ "{:,}".format(item.member_count) }}{% endfor %}

      - name: Get data
        run: |
          python -m mysoc_mailchimp segments --pattern "Interest: Demo" --order-by member_count --desc --json > data.json
          # join the two files
          # generate the message
          j2 --format=json template.md.j2 data.json > formatted_message.md
          # take this message and put it into a json file under the key 'message'
          jq -n --arg message "$(cat formatted_message.md)" '{"message": $message}' > payload-slack-content.json
        env:
          MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload-file-path: "./payload-slack-content.json"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEMOCRACY_WEBHOOK_URL }}
